### ISSUE TITLE
After Giants update (FS25) around certain parts of placebles the terrain can't be edited (raised/lowered)

### ISSUE THREAD

**Issue by THEGery** [Achimobil/FS25_FreeTerraformingAndPainting#5]
Since the first big Giants Update to FS25, there is no possibility to adjust the terrain in or around some placebles, like the smallest cowbarn (The one that gives milk). I tried to minimise the gap between the entrance/exit ramps and the ground after placeing the barn, by slightly raising the terrain, but I couldn't do it within a small radious from the ramp.
Before the Giants update I could do it. 

I would like to have the ability again to be able to manipulate the terrain in, or around any placeble. As that is the only way to make the sorroundings nice :)

**Comment by Achimobil** [comment]
There are you wrong here.  This Mod is to make the terraforming without costs. Where you can terraform is not changed.
